---
version: '3.4'
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.25.0
    ports:
    - 8080:8080
    - 50051:50051
    volumes:
    - ./docker_data/weaviate:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-ollama'
      ENABLE_MODULES: 'text2vec-ollama'
      CLUSTER_HOSTNAME: 'weaviate-0'
  text2vec-ollama:
    image: ollama/ollama:0.1.37
    container_name: text2vec-ollama
    volumes:
    - ./docker_data/text2vec_ollama:/root/.ollama
    environment:
      ENABLE_CUDA: '0'
  generative-ollama:
    image: ollama/ollama:0.1.37
    container_name: generative-ollama
    volumes:
    - ./docker_data/generative_ollama:/root/.ollama
    environment:
      ENABLE_CUDA: '0'
...